#!/bin/bash


show_result() {
#	echo ""
#	echo ""
	r=$1
	if [ $r -ne 0 ]; then
		echo -e "\e[31m->Test FAIL \e[0m"
		while [ 1 ]
		do
			sleep 1
		done
	fi
}

count = 0
while [ 1 ]
do

# print header
echo ""
echo ""
echo ""
echo "-------------------------"
let "count = $count + 1"
echo count=$count
echo "-------------------------"
echo $1
echo ""

./auto_wlan0

./auto_bt

./auto_usb_speed
#r=$?
#show_result $r

./auto_ping $1

./auto_csi
#r=$?
#show_result $r

sleep 1
done

#echo -e "\e[32m->Test OK, sys will power off in 5s \e[0m"
#n=5
#while [ $n -ge 0 ]
#do
#        echo -ne $n.
#        sleep 1
#        let "n = $n - 1"
#done
#echo ""
#poweroff
