#!/bin/bash


show_result() {
	echo ""
	echo ""
	r=$1
	if [ $r -ne 0 ]; then
		echo -e "\e[31m->Test FAIL \e[0m"
		while [ 1 ]
		do
			sleep 1
		done
	fi
}

echo $1
./auto_usb
r=$?
show_result $r
./auto_iperf $1
r=$?
show_result $r
./auto_csi
r=$?
show_result $r

echo -e "\e[32m->Test OK, sys will power off in 5s \e[0m"
n=5
while [ $n -ge 0 ]
do
        echo -ne $n.
        sleep 1
        let "n = $n - 1"
done
echo ""
poweroff
